#!/bin/bash

if [ $# -eq 0 ]; then
	echo "Usage: ./pushover <message> [title] [sound]"
	exit
fi

MESSAGE=$1
TITLE=$2
SOUND=$3

if [ $# -lt 2 ]; then
	TITLE="`whoami`@${HOSTNAME}"
fi

# Set your tokens
APP_TOKEN="APPTOKEN"
USER_TOKEN="USERTOKEN"

wget https://api.pushover.net/1/messages.json --post-data="token=$APP_TOKEN&user=$USER_TOKEN&message=$MESSAGE&title=$TITLE&sound=$SOUND" -qO- > /dev/null 2>&1 &